import { Lesson, ReferenceCategory } from './types';

export const lessons: Lesson[] = [
  {
    id: 'basic-movement',
    title: 'Basic Movement',
    description: 'Learn to move the cursor with h, j, k, l',
    keys: 'h j k l',
    icon: '🎯',
    steps: [
      {
        instruction: 'Press <kbd>l</kbd> to move the cursor right to the "X"',
        hint: 'The "l" key moves right (think: "l" looks like the number 1, pointing right)',
        initialContent: ['Move cursor here ->  X'],
        initialCursor: { line: 0, col: 18 },
        validate: (state) => state.cursor.col >= 21,
      },
      {
        instruction: 'Press <kbd>h</kbd> to move the cursor left back to the start',
        hint: 'The "h" key moves left (it\'s on the left side of j/k/l)',
        validate: (state) => state.cursor.col <= 5,
      },
      {
        instruction: 'Press <kbd>j</kbd> to move down to line 2',
        hint: 'The "j" key moves down (think: "j" has a hook that points down)',
        initialContent: ['Line 1: Start here', 'Line 2: Move down to this line', 'Line 3: Then move here'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.line === 1,
      },
      {
        instruction: 'Press <kbd>k</kbd> to move back up to line 1',
        hint: 'The "k" key moves up (it points upward)',
        validate: (state) => state.cursor.line === 0,
      },
      {
        instruction: 'Now try using <kbd>j</kbd> twice to reach line 3',
        hint: 'Press j two times to move down two lines',
        validate: (state) => state.cursor.line === 2,
      },
    ],
  },
  {
    id: 'word-movement',
    title: 'Word Movement',
    description: 'Move by words with w, b, e',
    keys: 'w b e',
    icon: '📝',
    steps: [
      {
        instruction: 'Press <kbd>w</kbd> to jump to the next word',
        hint: '"w" moves to the start of the next word',
        initialContent: ['The quick brown fox jumps over the lazy dog'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.col === 4,
      },
      {
        instruction: 'Press <kbd>w</kbd> two more times to reach "brown"',
        hint: 'Keep pressing w to jump word by word',
        validate: (state) => state.cursor.col === 10,
      },
      {
        instruction: 'Press <kbd>b</kbd> to go back to the previous word',
        hint: '"b" moves backward to the start of the previous word',
        validate: (state) => state.cursor.col === 4,
      },
      {
        instruction: 'Press <kbd>e</kbd> to move to the end of the current word',
        hint: '"e" moves to the end of the word',
        validate: (state) => state.cursor.col === 8,
      },
      {
        instruction: 'Use <kbd>w</kbd> to navigate to "jumps"',
        hint: 'Press w multiple times until you reach "jumps"',
        validate: (state) => state.cursor.col === 20,
      },
    ],
  },
  {
    id: 'line-movement',
    title: 'Line Movement',
    description: 'Jump to line start/end with 0, $, ^',
    keys: '0 $ ^',
    icon: '↔️',
    steps: [
      {
        instruction: 'Press <kbd>$</kbd> to jump to the end of the line',
        hint: '"$" takes you to the last character of the line',
        initialContent: ['  function hello() { return "world"; }'],
        initialCursor: { line: 0, col: 10 },
        validate: (state) => state.cursor.col === 38,
      },
      {
        instruction: 'Press <kbd>0</kbd> to jump to the very beginning of the line',
        hint: '"0" takes you to column 0 (absolute start)',
        validate: (state) => state.cursor.col === 0,
      },
      {
        instruction: 'Press <kbd>^</kbd> to jump to the first non-space character',
        hint: '"^" skips leading whitespace and goes to first character',
        validate: (state) => state.cursor.col === 2,
      },
    ],
  },
  {
    id: 'file-movement',
    title: 'File Movement',
    description: 'Navigate the file with gg, G',
    keys: 'gg G',
    icon: '📄',
    steps: [
      {
        instruction: 'Press <kbd>G</kbd> (capital G) to go to the last line',
        hint: 'Shift+g takes you to the bottom of the file',
        initialContent: [
          'Line 1: First line of the file',
          'Line 2: Some content here',
          'Line 3: More content',
          'Line 4: Even more content',
          'Line 5: Last line of the file',
        ],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.line === 4,
      },
      {
        instruction: 'Press <kbd>gg</kbd> to go back to the first line',
        hint: 'Press g twice quickly to go to the top',
        validate: (state) => state.cursor.line === 0,
      },
    ],
  },
  {
    id: 'insert-mode',
    title: 'Insert Mode',
    description: 'Enter insert mode with i, a, o, O',
    keys: 'i a o O',
    icon: '✏️',
    steps: [
      {
        instruction: 'Press <kbd>i</kbd> to enter insert mode, then type "Hello" and press <kbd>Escape</kbd>',
        hint: '"i" enters insert mode at the cursor position',
        initialContent: ['Type here: '],
        initialCursor: { line: 0, col: 11 },
        validate: (state) => state.lines[0].includes('Hello') && state.mode === 'normal',
      },
      {
        instruction: 'Press <kbd>a</kbd> to append after cursor, type " World" and press <kbd>Escape</kbd>',
        hint: '"a" enters insert mode after the cursor (append)',
        initialContent: ['Hello'],
        initialCursor: { line: 0, col: 4 },
        validate: (state) => state.lines[0].includes('World') && state.mode === 'normal',
      },
      {
        instruction: 'Press <kbd>o</kbd> to open a new line below, type "New line" and press <kbd>Escape</kbd>',
        hint: '"o" opens a new line below and enters insert mode',
        initialContent: ['First line', 'Third line'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.lines.length >= 3 && state.lines[1].includes('New line') && state.mode === 'normal',
      },
      {
        instruction: 'Press <kbd>O</kbd> (capital O) to open a new line above, type "Above" and press <kbd>Escape</kbd>',
        hint: '"O" (shift+o) opens a new line above',
        initialContent: ['Second line'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.lines.length >= 2 && state.lines[0].includes('Above') && state.mode === 'normal',
      },
    ],
  },
  {
    id: 'insert-advanced',
    title: 'Advanced Insert',
    description: 'More insert commands: I, A',
    keys: 'I A',
    icon: '📝',
    steps: [
      {
        instruction: 'Press <kbd>A</kbd> to append at end of line, type "!" and press <kbd>Escape</kbd>',
        hint: '"A" jumps to end of line and enters insert mode',
        initialContent: ['Hello World'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.lines[0].endsWith('!') && state.mode === 'normal',
      },
      {
        instruction: 'Press <kbd>I</kbd> to insert at beginning of text, type ">>> " and press <kbd>Escape</kbd>',
        hint: '"I" jumps to first non-space char and enters insert mode',
        initialContent: ['    Some indented text'],
        initialCursor: { line: 0, col: 10 },
        validate: (state) => state.lines[0].includes('>>> ') && state.mode === 'normal',
      },
    ],
  },
  {
    id: 'delete-commands',
    title: 'Delete Commands',
    description: 'Delete text with x, dd, dw',
    keys: 'x dd dw',
    icon: '🗑️',
    steps: [
      {
        instruction: 'Press <kbd>x</kbd> to delete the character under the cursor',
        hint: '"x" deletes the character at cursor position',
        initialContent: ['Hellxo World'],
        initialCursor: { line: 0, col: 4 },
        validate: (state) => state.lines[0] === 'Hello World',
      },
      {
        instruction: 'Press <kbd>dd</kbd> to delete the entire line',
        hint: '"dd" deletes the current line',
        initialContent: ['Keep this line', 'Delete this line', 'Keep this too'],
        initialCursor: { line: 1, col: 0 },
        validate: (state) => state.lines.length === 2 && !state.lines.some(l => l.includes('Delete')),
      },
      {
        instruction: 'Press <kbd>dw</kbd> to delete from cursor to next word',
        hint: '"dw" deletes from cursor to the start of next word',
        initialContent: ['Delete the REMOVE word here'],
        initialCursor: { line: 0, col: 11 },
        validate: (state) => state.lines[0] === 'Delete the word here',
      },
    ],
  },
  {
    id: 'change-commands',
    title: 'Change Commands',
    description: 'Change text with c, cc, cw',
    keys: 'c cc cw',
    icon: '🔄',
    steps: [
      {
        instruction: 'Press <kbd>cw</kbd> to change word, type "updated" and press <kbd>Escape</kbd>',
        hint: '"cw" deletes word and enters insert mode',
        initialContent: ['The old value is here'],
        initialCursor: { line: 0, col: 4 },
        validate: (state) => state.lines[0].includes('updated') && state.mode === 'normal',
      },
      {
        instruction: 'Press <kbd>cc</kbd> to change entire line, type "Brand new line" and press <kbd>Escape</kbd>',
        hint: '"cc" clears line and enters insert mode',
        initialContent: ['Replace this entire line please'],
        initialCursor: { line: 0, col: 10 },
        validate: (state) => state.lines[0] === 'Brand new line' && state.mode === 'normal',
      },
    ],
  },
  {
    id: 'yank-paste',
    title: 'Copy & Paste',
    description: 'Copy and paste with yy, p, P',
    keys: 'yy p P',
    icon: '📋',
    steps: [
      {
        instruction: 'Press <kbd>yy</kbd> to copy (yank) the current line',
        hint: '"yy" yanks (copies) the entire current line',
        initialContent: ['Copy this line', 'Another line'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => {
          return state.registers && state.registers['"']?.includes('Copy this line');
        },
      },
      {
        instruction: 'Move down with <kbd>j</kbd> and press <kbd>p</kbd> to paste below',
        hint: '"p" pastes after/below cursor',
        validate: (state) => state.lines.length >= 3 && state.lines[2]?.includes('Copy this line'),
      },
      {
        instruction: 'Press <kbd>P</kbd> (capital P) to paste above the current line',
        hint: '"P" pastes before/above cursor',
        initialContent: ['First line', 'Second line'],
        initialCursor: { line: 1, col: 0 },
        validate: (state, _prev) => {
          if (!_prev) return false;
          return state.lines.length > _prev.lines.length;
        },
      },
    ],
  },
  {
    id: 'visual-mode',
    title: 'Visual Mode',
    description: 'Select text with v, V',
    keys: 'v V',
    icon: '🎨',
    steps: [
      {
        instruction: 'Press <kbd>v</kbd> to enter visual mode',
        hint: '"v" starts character-wise visual selection',
        initialContent: ['Select some text from this line'],
        initialCursor: { line: 0, col: 7 },
        validate: (state) => state.mode === 'visual',
      },
      {
        instruction: 'Use <kbd>l</kbd> or <kbd>w</kbd> to extend selection, then press <kbd>d</kbd> to delete',
        hint: 'Move to select more text, then "d" deletes selection',
        validate: (state) => state.mode === 'normal' && state.lines[0].length < 31,
      },
      {
        instruction: 'Press <kbd>V</kbd> to select entire line, then <kbd>y</kbd> to yank',
        hint: '"V" selects whole line, "y" copies the selection',
        initialContent: ['First line to select', 'Second line'],
        initialCursor: { line: 0, col: 5 },
        validate: (state) => state.mode === 'normal' && state.registers['"']?.includes('First line'),
      },
    ],
  },
  {
    id: 'search',
    title: 'Search',
    description: 'Find text with /, n, N',
    keys: '/ n N',
    icon: '🔍',
    steps: [
      {
        instruction: 'Type <kbd>/</kbd> then "fox" and press <kbd>Enter</kbd> to search',
        hint: '"/" starts a forward search',
        initialContent: ['The quick brown fox jumps', 'over the lazy fox', 'in the fox den'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.col === 16 && state.cursor.line === 0,
      },
      {
        instruction: 'Press <kbd>n</kbd> to find the next occurrence',
        hint: '"n" goes to next match',
        validate: (state) => state.cursor.line === 1,
      },
      {
        instruction: 'Press <kbd>N</kbd> to find the previous occurrence',
        hint: '"N" goes to previous match',
        validate: (state) => state.cursor.line === 0,
      },
    ],
  },
  {
    id: 'command-mode',
    title: 'Command Mode',
    description: 'Execute commands with :',
    keys: ': w q',
    icon: '⌨️',
    steps: [
      {
        instruction: 'Type <kbd>:w</kbd> and press <kbd>Enter</kbd> to save (simulated)',
        hint: '":w" writes (saves) the file',
        initialContent: ['Some content to save'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.message.includes('saved'),
      },
      {
        instruction: 'Type <kbd>:3</kbd> and press <kbd>Enter</kbd> to go to line 3',
        hint: '":number" goes to that line',
        initialContent: ['Line 1', 'Line 2', 'Line 3', 'Line 4', 'Line 5'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.line === 2,
      },
    ],
  },
  {
    id: 'replace-char',
    title: 'Replace Character',
    description: 'Replace single characters with r',
    keys: 'r',
    icon: '🔤',
    steps: [
      {
        instruction: 'Press <kbd>r</kbd> then <kbd>a</kbd> to replace the character under cursor with "a"',
        hint: '"r" + char replaces current character without entering insert mode',
        initialContent: ['Hxllo World'],
        initialCursor: { line: 0, col: 1 },
        validate: (state) => state.lines[0] === 'Hallo World',
      },
      {
        instruction: 'Move to the "W" and press <kbd>r</kbd> then <kbd>w</kbd> to make it lowercase',
        hint: 'Use movement keys first, then r + character',
        initialContent: ['Hello World'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.lines[0] === 'Hello world',
      },
    ],
  },
  {
    id: 'find-char',
    title: 'Find Character',
    description: 'Jump to characters with f, F',
    keys: 'f F',
    icon: '🏃',
    steps: [
      {
        instruction: 'Press <kbd>f</kbd> then <kbd>x</kbd> to jump forward to "x"',
        hint: '"f" + char finds next occurrence of char in line',
        initialContent: ['Find the x in this text'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.col === 9,
      },
      {
        instruction: 'Press <kbd>F</kbd> then <kbd>t</kbd> to jump backward to "t"',
        hint: '"F" + char finds previous occurrence of char',
        initialContent: ['Jump to the target here'],
        initialCursor: { line: 0, col: 20 },
        validate: (state) => state.cursor.col === 12,
      },
    ],
  },
  {
    id: 'counts',
    title: 'Counts & Repeats',
    description: 'Repeat commands with numbers',
    keys: '2j 3w 5x',
    icon: '🔢',
    steps: [
      {
        instruction: 'Type <kbd>3j</kbd> to move down 3 lines at once',
        hint: 'Number before command repeats it that many times',
        initialContent: ['Line 1', 'Line 2', 'Line 3', 'Line 4', 'Line 5'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.line === 3,
      },
      {
        instruction: 'Type <kbd>2w</kbd> to move forward 2 words',
        hint: '2w = move forward two words',
        initialContent: ['one two three four five'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.cursor.col === 8,
      },
      {
        instruction: 'Type <kbd>3x</kbd> to delete 3 characters',
        hint: '3x = delete 3 characters',
        initialContent: ['XXXHELLO'],
        initialCursor: { line: 0, col: 0 },
        validate: (state) => state.lines[0] === 'HELLO',
      },
    ],
  },
];

export const referenceCategories: ReferenceCategory[] = [
  {
    title: 'Movement',
    commands: [
      { key: 'h', description: 'Move left' },
      { key: 'j', description: 'Move down' },
      { key: 'k', description: 'Move up' },
      { key: 'l', description: 'Move right' },
      { key: 'w', description: 'Next word start' },
      { key: 'b', description: 'Previous word start' },
      { key: 'e', description: 'End of word' },
      { key: '0', description: 'Line start' },
      { key: '$', description: 'Line end' },
      { key: '^', description: 'First non-space' },
      { key: 'gg', description: 'File start' },
      { key: 'G', description: 'File end' },
      { key: 'f{c}', description: 'Find char forward' },
      { key: 'F{c}', description: 'Find char backward' },
    ],
  },
  {
    title: 'Insert Mode',
    commands: [
      { key: 'i', description: 'Insert before cursor' },
      { key: 'a', description: 'Append after cursor' },
      { key: 'I', description: 'Insert at line start' },
      { key: 'A', description: 'Append at line end' },
      { key: 'o', description: 'New line below' },
      { key: 'O', description: 'New line above' },
      { key: 'Esc', description: 'Exit insert mode' },
    ],
  },
  {
    title: 'Editing',
    commands: [
      { key: 'x', description: 'Delete character' },
      { key: 'r{c}', description: 'Replace character' },
      { key: 'dd', description: 'Delete line' },
      { key: 'dw', description: 'Delete word' },
      { key: 'D', description: 'Delete to end of line' },
      { key: 'cc', description: 'Change line' },
      { key: 'cw', description: 'Change word' },
      { key: 'C', description: 'Change to end of line' },
      { key: 's', description: 'Delete char & insert' },
      { key: 'S', description: 'Delete line & insert' },
      { key: 'J', description: 'Join lines' },
    ],
  },
  {
    title: 'Copy & Paste',
    commands: [
      { key: 'yy', description: 'Yank (copy) line' },
      { key: 'yw', description: 'Yank word' },
      { key: 'p', description: 'Paste after' },
      { key: 'P', description: 'Paste before' },
    ],
  },
  {
    title: 'Visual Mode',
    commands: [
      { key: 'v', description: 'Visual character mode' },
      { key: 'V', description: 'Visual line mode' },
      { key: 'd', description: 'Delete selection' },
      { key: 'y', description: 'Yank selection' },
      { key: 'c', description: 'Change selection' },
    ],
  },
  {
    title: 'Search',
    commands: [
      { key: '/', description: 'Search forward' },
      { key: 'n', description: 'Next match' },
      { key: 'N', description: 'Previous match' },
      { key: '*', description: 'Search word under cursor' },
    ],
  },
  {
    title: 'Commands',
    commands: [
      { key: ':w', description: 'Save file' },
      { key: ':q', description: 'Quit' },
      { key: ':wq', description: 'Save and quit' },
      { key: ':{n}', description: 'Go to line n' },
      { key: ':s/a/b', description: 'Substitute a with b' },
    ],
  },
];
